server:
  port: 3030
cors:
  originPatterns: http://localhost:3030,https://erudio.com.br
file:
  upload-dir: /home/run/work/rest-with-springboot-and-java/
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_springboot?useTimezone=true?serverTimezone=UTC
    username: root
    password: "#!d0D0d0D0d0#!"
  devtools:
    re
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  pathsToMatch:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true